# Generated by Django 2.1.1 on 2019-02-28 14:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='avatars'),
        ),
    ]
