# Generated by Django 2.1.1 on 2019-02-28 14:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0002_auto_20190228_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatars/wallls.com_119414.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatars/wallls.com_119414.jpg', upload_to='avatars'),
        ),
    ]
