# Generated by Django 2.1.1 on 2019-03-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0003_auto_20190228_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-time']},
        ),
    ]
