# Generated by Django 2.1.5 on 2019-03-11 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0003_auto_20190311_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhuser',
            name='blinduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mhuser',
            name='shequ',
            field=models.CharField(default='oxygen', max_length=50),
        ),
    ]
