# Generated by Django 2.1.5 on 2019-03-03 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0004_auto_20190302_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('value', models.FloatField(default='', verbose_name='具体数值')),
                ('own', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mhuser.NormalUser', verbose_name='条目所有者')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='OxygenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('value', models.FloatField(default='', verbose_name='具体数值')),
                ('own', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mhuser.NormalUser', verbose_name='条目所有者')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='PressureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('value', models.FloatField(default='', verbose_name='具体数值')),
                ('own', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mhuser.NormalUser', verbose_name='条目所有者')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='TemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('value', models.FloatField(default='', verbose_name='具体数值')),
                ('own', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mhuser.NormalUser', verbose_name='条目所有者')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.RemoveField(
            model_name='data',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='data',
            name='own',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
