# Generated by Django 2.2.1 on 2019-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0004_auto_20190311_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhuser',
            name='blinduser',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
