# Generated by Django 2.1.5 on 2019-03-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0005_auto_20190303_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhuser',
            name='deviceid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
