# Generated by Django 2.1.5 on 2019-03-08 06:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', ckeditor.fields.RichTextField(verbose_name='正文')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(default='', max_length=20, verbose_name='标签')),
                ('views', models.IntegerField(default=0, verbose_name='观看次数')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
