# Generated by Django 2.1.5 on 2019-02-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover',
        ),
    ]
