# Generated by Django 2.1.5 on 2019-03-08 06:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000, verbose_name='留言')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
