# Generated by Django 2.1.5 on 2019-03-08 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explain', '0001_initial'),
        ('mhuser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='explain',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explain',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mhuser.Match'),
        ),
    ]
