# Generated by Django 2.1.5 on 2019-03-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explain',
            options={'ordering': ['-time']},
        ),
    ]
