# Generated by Django 2.1.5 on 2019-03-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0003_auto_20190311_0112'),
        ('explain', '0002_auto_20190308_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explain',
            name='match',
        ),
        migrations.AddField(
            model_name='explain',
            name='touserid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mhuser.NormalUser'),
        ),
    ]
