# Generated by Django 2.1.5 on 2019-03-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0003_auto_20190311_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='explain',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
