# Generated by Django 2.1.5 on 2019-03-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0004_auto_20190311_0638'),
        ('explain', '0004_explain_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='explain',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mhuser.Match'),
        ),
    ]
