# Generated by Django 2.1.5 on 2019-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0005_explain_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explain',
            name='read',
            field=models.CharField(default=False, max_length=1),
        ),
    ]
