# Generated by Django 2.1.7 on 2019-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0006_auto_20190312_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explain',
            name='read',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
