# Generated by Django 2.1.5 on 2019-03-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='品名')),
                ('cover1', models.ImageField(default=None, upload_to='device/Cover')),
                ('cover2', models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover')),
                ('cover3', models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover')),
                ('cover4', models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover')),
                ('cover5', models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover')),
                ('label', models.TextField(default='', max_length=50, verbose_name='标签')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('detailimage1', models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage')),
                ('detailimage2', models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage')),
                ('detailimage3', models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage')),
                ('detailimage4', models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage')),
                ('detailimage5', models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage')),
            ],
        ),
    ]
