# Generated by Django 2.1.1 on 2019-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20190301_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='detailimage1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage'),
        ),
        migrations.AlterField(
            model_name='device',
            name='detailimage2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage'),
        ),
        migrations.AlterField(
            model_name='device',
            name='detailimage3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage'),
        ),
        migrations.AlterField(
            model_name='device',
            name='detailimage4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage'),
        ),
        migrations.AlterField(
            model_name='device',
            name='detailimage5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/detailimage'),
        ),
    ]
