# Generated by Django 2.1.1 on 2019-03-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20190301_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cover1',
            field=models.ImageField(default=None, upload_to='device/Cover'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cover2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cover3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cover4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cover5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='device/Cover'),
        ),
    ]
