# Generated by Django 2.1.5 on 2019-02-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='头像'),
        ),
    ]
