# Generated by Django 2.1.5 on 2019-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default='', null=True, upload_to='', verbose_name='封面'),
        ),
    ]
