# Generated by Django 2.1.5 on 2019-02-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0002_auto_20190218_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='头像'),
        ),
    ]
