# Generated by Django 2.1.5 on 2019-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0002_auto_20190215_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='封面'),
        ),
    ]
