# Generated by Django 2.1.5 on 2019-02-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0003_auto_20190211_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruser',
            name='usertype',
            field=models.CharField(default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='usertype',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
