# Generated by Django 2.1.5 on 2019-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0005_auto_20190212_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolg',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
