# Generated by Django 2.1.5 on 2019-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0006_bolg_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolg',
            name='id',
        ),
        migrations.AlterField(
            model_name='bolg',
            name='title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
