# Generated by Django 2.1.5 on 2019-02-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0007_auto_20190212_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommon',
            name='commont',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='commonreply',
            name='commont',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
