# Generated by Django 2.1.5 on 2019-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0008_auto_20190212_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommon',
            name='commont',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bolg',
            name='article',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='commonreply',
            name='commont',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
