# Generated by Django 2.1.5 on 2019-02-15 05:45

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myhealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('followed_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealth.Blog', verbose_name='被评论对象')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='BottomComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('followed_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.BlogComment', verbose_name='被评论对象')),
                ('followed_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.BottomComment', verbose_name='评论的评论')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
