# Generated by Django 2.1.5 on 2019-02-15 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
        ('myhealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='bottomcomment',
            name='followed_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.BlogComment', verbose_name='被评论对象'),
        ),
        migrations.AddField(
            model_name='bottomcomment',
            name='followed_self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.BottomComment', verbose_name='评论的评论'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='followed_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealth.Blog', verbose_name='被评论对象'),
        ),
    ]
