# Generated by Django 2.1.5 on 2019-02-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190218_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomcomment',
            name='followed_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.BlogComment', verbose_name='被评论对象'),
        ),
    ]
